// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwyzodyplpzxmcdepzmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53eXpvZHlwbHB6eG1jZGVwem11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NDA5MTMsImV4cCI6MjA1NDMxNjkxM30.mPM7wFAHBh48lNShmGdTARtjTmUBWkqvgRapYpKf-S0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);